server:
  port: 5454

spring:
  application:
    name: Crypto Trading Platform

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crypto_trading_platform
    username: root
    password: Void@786

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

stripe:
  api:
    key: StripeTestApiKeyHere

razorpay:
  api:
    key: ${RAZORPAY_API_KEY}
    secret: ${RAZORPAY_API_SECRET}

coingecko:
  api:
    key: ${COINGECKO_API_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}